FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG GOOGLE_CLIENT_ID
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG GOOGLE_CLIENT_SECRET
ARG PUSHER_APP_ID
ARG NEXT_PUBLIC_PUSHER_APP_KEY
ARG PUSHER_APP_SECRET

ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
ENV UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV PUSHER_APP_ID=$PUSHER_APP_ID
ENV NEXT_PUBLIC_PUSHER_APP_KEY=$NEXT_PUBLIC_PUSHER_APP_KEY
ENV PUSHER_APP_SECRET=$PUSHER_APP_SECRET


RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]